@startuml  
state 診察予約システム{
state entry <<entryPoint>>
state exit <<exitPoint>>
state c <<choice>>
state c2 <<choice>>
entry --> メニュー画面
メニュー画面 --> c
c --> 予約と確認画面 :予約と確認ボタンを押す
c --> 今の順番画面 :今の順番ボタンを押す
予約と確認画面 --> c2
c2 --> あなたの順番画面 :名前と電話番号を入力して、登録ボタンを押す
c2 --> あなたの順番画面 :名前か電話番号を入力して、確認ボタンを押す
c2 --> メニュー画面 :名前か電話番号を入力して、取消ボタンを押す
今の順番画面 --> メニュー画面 :メニューボタンを押す
あなたの順番画面 --> メニュー画面 :メニューボタンを押す
メニュー画面 --> exit
}
[*] --> entry :接続
exit --> [*]
@enduml