@startuml  
object "<u>高橋洋平：顧客</u>" as k1{

}
object "<u>高田利恵：顧客</u>" as k2{

}
object "<u>大坪直之：顧客</u>" as k3{

}
object "<u>テレビ：商品</u>" as s1{

}
object "<u>冷蔵庫：商品</u>" as s2{

}
object "<u>プロジェクタ：商品</u>" as s3{

}
object "<u>注文：注文</u>" as t1{

}
object "<u>重要顧客：重要顧客</u>" as j{

}
j -- k1
k1 -- t1
k2 -- t1
t1 -- s1
t1 -- s2
@enduml